// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncServer;

#nullable disable

namespace SyncServer.Migrations
{
    [DbContext(typeof(SyncDBContext))]
    [Migration("20260721101110_ModelChange")]
    partial class ModelChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncServer.Dict", b =>
                {
                    b.Property<DateTime>("Modification_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DBID")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateRec")
                        .HasColumnType("date");

                    b.Property<byte>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("Score");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Phrase")
                        .HasColumnType("boolean");

                    b.Property<byte>("Relevation")
                        .HasColumnType("smallint");

                    b.Property<bool>("Spot")
                        .HasColumnType("boolean");

                    b.Property<string>("TopicName")
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usersel")
                        .HasColumnType("boolean");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Modification_Time", "DBID");

                    b.HasIndex("Modification_Time");

                    b.ToTable("dict");
                });

            modelBuilder.Entity("SyncServer.Topic", b =>
                {
                    b.Property<DateTime>("Modification_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DBID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Modification_Time", "DBID");

                    b.HasIndex("Modification_Time");

                    b.ToTable("topic");
                });
#pragma warning restore 612, 618
        }
    }
}
