// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SyncServer;

#nullable disable

namespace SyncServer.Migrations
{
    [DbContext(typeof(SyncDBContext))]
    partial class SyncDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SyncServer.Dict", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Number");

                    b.Property<long>("DBID")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("DateRec")
                        .HasColumnType("date");

                    b.Property<byte>("Grade")
                        .HasColumnType("smallint")
                        .HasColumnName("Score");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Modification_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Phrase")
                        .HasColumnType("boolean");

                    b.Property<byte>("Relevation")
                        .HasColumnType("smallint");

                    b.Property<bool>("Spot")
                        .HasColumnType("boolean");

                    b.Property<int?>("Topic")
                        .HasColumnType("integer");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usersel")
                        .HasColumnType("boolean");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "DBID");

                    b.HasIndex("DateRec");

                    b.HasIndex("Translation");

                    b.HasIndex("Word");

                    b.ToTable("Dict");
                });

            modelBuilder.Entity("SyncServer.Topic", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("DBID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Modification_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "DBID");

                    b.HasIndex("Name");

                    b.ToTable("topic");
                });
#pragma warning restore 612, 618
        }
    }
}
